---
title: "Thesis Firm Fixed Effects Redo"
output: html_document
---

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
library(reshape2)
library(dplyr)
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
setwd("/Users/RaymonYue/Desktop/Honors Thesis")
trucost_select <- read.csv("trucost_sus.csv", row.names=NULL)
trucost_select <-filter(trucost_select, year>=2013)
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
sus<-read.csv("sus.csv")
sus_keep <- c("Ticker","Company.Name","ISIN","Industry","MSCI.Country",
             "GICS.Industry.Group","Equity..Style.Box..Long.")

sus_select <- sus[sus_keep]
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
ratings_1618<-read.csv("ESG_ratings.csv")
ratings_1618<-filter(ratings_1618,
                     rowSums(ratings_1618[,2:91],na.rm=T)!=0)
ratings_1618$"12f"<-rowMeans(ratings_1618[,2:7], na.rm=T)
ratings_1618$"12l"<-rowMeans(ratings_1618[,8:13], na.rm=T)
ratings_1618$"13f"<-rowMeans(ratings_1618[,14:19], na.rm=T)
ratings_1618$"13l"<-rowMeans(ratings_1618[,20:25], na.rm=T)
ratings_1618$"14f"<-rowMeans(ratings_1618[,26:31], na.rm=T)
ratings_1618$"14l"<-rowMeans(ratings_1618[,32:37], na.rm=T)
ratings_1618$"15f"<-rowMeans(ratings_1618[,38:43], na.rm=T)
ratings_1618$"15l"<-rowMeans(ratings_1618[,44:49], na.rm=T)
ratings_1618$"16f"<-rowMeans(ratings_1618[,50:55], na.rm=T)
ratings_1618$"16l"<-rowMeans(ratings_1618[,56:61], na.rm=T)
ratings_1618$"17f"<-rowMeans(ratings_1618[,62:67], na.rm=T)
ratings_1618$"17l"<-rowMeans(ratings_1618[,68:73], na.rm=T)
ratings_1618$"18f"<-rowMeans(ratings_1618[,74:79], na.rm=T)
ratings_1618$"18l"<-rowMeans(ratings_1618[,80:85], na.rm=T)
ratings_1618$"19f"<-rowMeans(ratings_1618[,86:91], na.rm=T)
ratings_1618$"12"<-rowMeans(ratings_1618[,2:13], na.rm=T)
ratings_1618$"13"<-rowMeans(ratings_1618[,14:25], na.rm=T)
ratings_1618$"14"<-rowMeans(ratings_1618[,26:37], na.rm=T)
ratings_1618$"15"<-rowMeans(ratings_1618[,38:49], na.rm=T)
ratings_1618$"16"<-rowMeans(ratings_1618[,50:61], na.rm=T)
ratings_1618$"17"<-rowMeans(ratings_1618[,62:73], na.rm=T)
ratings_1618$"18"<-rowMeans(ratings_1618[,74:85], na.rm=T)
ratings_1618$"19"<-rowMeans(ratings_1618[,86:91], na.rm=T)

mean_rate<-subset(ratings_1618,select=c("Ticker","12f","12l","13f","13l","14f","14l",
                                        "15f","15l","16f","16l","17f","17l",
                                        "18f","18l","19f","12","13","14",
                                        "15","16","17","18","19"))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
mean_rate$pretreat<-rowSums(mean_rate[,2:9],na.rm=T)>0
mean_rate$posttreat<-!is.na(mean_rate[,10])
mean_rate$treatment_group <- ((mean_rate$posttreat-mean_rate$pretreat)==1)
mean_rate$control_group <- (mean_rate$posttreat&mean_rate$pretreat)
mean_rate$treat_later_group <- !(mean_rate$posttreat|mean_rate$pretreat)
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
mean_rate<-subset(mean_rate,select=c("Ticker","treatment_group",
                                        "control_group","treat_later_group","16f","16l"))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
sus_select <- merge(sus_select, mean_rate, by = "Ticker")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
library(stringr)
trucost_select$Company.Name <- str_replace_all(trucost_select$Company.Name, "[[:punct:]]", "")
trucost_select$Company.Name <- tolower(trucost_select$Company.Name)
trucost_select$Company.Name <- str_replace_all(trucost_select$Company.Name, "incorporated", "inc")
trucost_select$Company.Name <- str_replace_all(trucost_select$Company.Name, "corporation", "corp")
trucost_select$Company.Name <- str_replace_all(trucost_select$Company.Name, "limited", "ltd")
trucost_select$Company.Name <- str_replace_all(trucost_select$Company.Name, "company", "co")
sus_select$Company.Name<-str_replace_all(sus_select$Company.Name, "[[:punct:]]", "")
sus_select$Company.Name <- tolower(sus_select$Company.Name)
sus_select$Company.Name <- str_replace_all(sus_select$Company.Name, "incorporated", "inc")
sus_select$Company.Name <- str_replace_all(sus_select$Company.Name, "corporation", "corp")
sus_select$Company.Name <- str_replace_all(sus_select$Company.Name, "limited", "ltd")
sus_select$Company.Name <- str_replace_all(sus_select$Company.Name, "company", "co")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
merged_sus_trucost <- merge(trucost_select, sus_select, by = "Company.Name", all.x = TRUE)
merged_sus_trucost$treat_year<-(merged_sus_trucost$year>2016)
length(merged_sus_trucost$ticker)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
has_pretreat<-unique(merged_sus_trucost[!merged_sus_trucost$treat_year,]$ticker)
merged_sus_trucost<-filter(merged_sus_trucost, ticker %in% has_pretreat)
length(merged_sus_trucost$ticker)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
merged_sus_trucost[is.na(merged_sus_trucost$treat_later_group),]$treat_later_group = FALSE
merged_sus_trucost<-filter(merged_sus_trucost, !treat_later_group)
length(merged_sus_trucost$ticker)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
aggregate(merged_sus_trucost$Company.Name, by=list(merged_sus_trucost$year), FUN=length)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
trucap<-read.csv("trucost_market_cap.csv")
trucap<-subset(trucap, select = c("ITEM5601", "ITEM6008", "ITEM8001", "ITEM9304"))
colnames(trucap)<-c("ticker","ISIN","Market.Cap","BM")
trucap<-filter(trucap, substr(as.character(ISIN),1,2)=="US")
trucap<-subset(trucap, select = c("ticker","Market.Cap", "BM"))
trucap<-trucap[!duplicated(trucap$ticker),]
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
merged_sus_trucost<-merge(merged_sus_trucost, trucap, by ="ticker", all.x = TRUE)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
trucost_sus_always_covered <- filter(merged_sus_trucost, !is.na(merged_sus_trucost$treatment_group))
length(trucost_sus_always_covered$ticker)
length(trucost_sus_always_covered[trucost_sus_always_covered$treatment_group,]$ticker)
length(trucost_sus_always_covered[!trucost_sus_always_covered$treatment_group,]$ticker)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
aggregate(!trucost_sus_always_covered$treatment_group, by=list(trucost_sus_always_covered$year), FUN=sum)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
filt <- merged_sus_trucost$treatment_group|is.na(merged_sus_trucost$treatment_group)
never_covered<-merged_sus_trucost[filt,]
never_covered$treatment_group[is.na(never_covered$treatment_group)] = 0
length(never_covered[!never_covered$treatment_group,]$ticker)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
aggregate(!never_covered$treatment_group, by=list(never_covered$year), FUN=sum)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
never_covered$did<-never_covered$treat_year*never_covered$treatment_group
trucost_sus_always_covered$did<-trucost_sus_always_covered$treat_year*trucost_sus_always_covered$treatment_group
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
never_cov_firm_ff_scope1<-lm(formula =log(GHG_Scope1+1)~did+factor(year)
                      +factor(Company.Name), data = never_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(never_cov_firm_ff_scope1)$coefficients[2,]
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_scope1<-lm(formula =log(GHG_Scope1+1)~did+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(always_cov_firm_ff_scope1)$coefficients[2,]
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
never_cov_firm_ff_scope2<-lm(formula =log(GHG_Scope2+1)~did+factor(year)
                      +factor(Company.Name), data = never_covered)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(never_cov_firm_ff_scope2)$coefficients[2,]
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_scope2<-lm(formula =log(GHG_Scope2+1)~did+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(always_cov_firm_ff_scope2)$coefficients[2,]
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_total<-lm(formula =log(Absolute_Direct_Indirect+0.001)~did+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(always_cov_firm_ff_total)$coefficients[2,]
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
never_cov_firm_ff_total<-lm(formula =log(Absolute_Direct_Indirect+0.001)~did+factor(year)
                      +factor(Company.Name), data = never_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(never_cov_firm_ff_total)$coefficients[2,]
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_total<-lm(formula =log(Absolute_Direct_Indirect+0.001)~did+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(always_cov_firm_ff_total)$coefficients[2,]
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
never_cov_firm_ff_total<-lm(formula =log(Absolute_Direct_Indirect+0.001)~did+factor(year)
                      +factor(Company.Name), data = never_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(never_cov_firm_ff_total)$coefficients[2,]
```



```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
merged_sus_trucost_copy<-merged_sus_trucost
merged_sus_trucost_copy[is.na(merged_sus_trucost_copy$treatment_group),]$treatment_group <- FALSE
merged_sus_trucost_copy$did<-
  merged_sus_trucost_copy$treat_year*merged_sus_trucost_copy$treatment_group
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
both_firm_ff_total<-lm(formula =log(Absolute_Direct_Indirect+0.001)~did+factor(year)
                      +factor(Company.Name), data = merged_sus_trucost_copy)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(both_firm_ff_total)$coefficients[2,]
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
both_firm_ff_scope1<-lm(formula =log(GHG_Scope1+1)~did+factor(year)
                      +factor(Company.Name), data = merged_sus_trucost_copy)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(both_firm_ff_scope1)$coefficients[2,]
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
both_firm_ff_scope2<-lm(formula =log(GHG_Scope2+1)~did+factor(year)
                      +factor(Company.Name), data = merged_sus_trucost_copy)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
summary(both_firm_ff_scope2)$coefficients[2,]
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(always_cov_firm_ff_total,
          always_cov_firm_ff_scope1,
          always_cov_firm_ff_scope2, 
          omit = c('year','Company.Name'), 
          add.lines=list(c('Year and Firm Fixed Effects', 'Yes','Yes','Yes'), 
                         c("Control Group", "Always Covered", "Always Covered", "Always Covered")))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(never_cov_firm_ff_total,
          never_cov_firm_ff_scope1,
          never_cov_firm_ff_scope2, 
          omit = c('year','Company.Name'), 
          add.lines=list(c('Year and Firm Fixed Effects', 'Yes','Yes','Yes'), 
                         c("Control Group", "Never Covered", "Never Covered", "Never Covered")))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(both_firm_ff_total, both_firm_ff_scope1, both_firm_ff_scope2, 
          omit = c('year','Company.Name'), 
          add.lines=list(c('Year and Firm Fixed Effects', 'Yes','Yes', 'Yes'), 
                         c("Control Group",  "Both Groups", "Both Groups","Both Groups")))
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
temp<-filter(merged_sus_trucost_copy, !treat_year)
condpara<-lm(log(Absolute_Direct_Indirect+0.001)~treatment_group*factor(year)+factor(Company.Name), data=temp)
condpara2<-lm(log(GHG_Scope2+1)~treatment_group*factor(year)+factor(Company.Name), data=temp)

condpara1<-lm(log(GHG_Scope1+1)~treatment_group*factor(year)+factor(Company.Name), data=temp)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(condpara, condpara1, condpara2, omit = c('gind',"Constant","Market.Cap","gind","BM","Company.Name"), add.lines=list(c('Fixed effects', 'Yes','Yes', 'Yes')))
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc<-read.csv("conference_call_data.csv")
cc_select = cc[,1:7]
cc_select = filter(cc_select, year<=2019)
cc_select = filter(cc_select, year>=2013)
cc_select<-rename(cc_select, ISIN = isin)
cc_merge<-merge(cc_select, sus_select, by = "ISIN", all.x=TRUE)
cc_merge<-filter(cc_merge, substr(cc_merge$ISIN,1,2)=="US")
cc_merge$treat_year<-(cc_merge$year>=2017)
length(cc_merge$ISIN)
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_filt<-unique(cc_merge[cc_merge$year<2017,]$ISIN)
cc_merge<-cc_merge[cc_merge$ISIN %in% cc_filt,]
cc_merge<-unique(cc_merge)
length(cc_merge$ISIN)
cc_merge[is.na(cc_merge$treat_later_group),]$treat_later_group<-FALSE
cc_merge<-filter(cc_merge, !treat_later_group)
length(cc_merge$ISIN)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
compustat_cc<- read.csv("compustat_cc.csv")
compustat_cc<-filter(compustat_cc, fyear == 2016)
compustat_cc<-subset(compustat_cc, select=c("tic", "gind", "naics"))
compustat_cc <- rename(compustat_cc, Ticker = tic)
compustat_cc$naics <- substr(compustat_cc$naics, 1, 2)
compustat_cc$gind <- substr(compustat_cc$gind, 1, 2)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_ticker<-read.csv("cc_ticker.csv")
cc_ticker<-subset(cc_ticker, select = c("ITEM5601", "ITEM6008", "ITEM8001", "ITEM9304"))
colnames(cc_ticker)<-c("Ticker", "ISIN", "Market.Cap", "BM")
compustat_cc<-merge(cc_ticker, compustat_cc, by="Ticker")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_merge<-merge(cc_merge, compustat_cc, by = "ISIN")
length(cc_merge$ISIN)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_merge[cc_merge$Ticker.y == "BUFF",]$gind = 30
cc_merge[cc_merge$Ticker.y == "GLTR",]$gind = 40
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_full<-cc_merge
cc_full[is.na(cc_full$treatment_group),]$treatment_group<-FALSE
```



```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_merge_covered<-filter(cc_merge, !is.na(cc_merge$treatment_group))
length(cc_merge_covered[cc_merge_covered$treatment_group,]$ISIN)
length(cc_merge_covered[!cc_merge_covered$treatment_group,]$ISIN)
length(cc_merge[is.na(cc_merge$treatment_group),]$ISIN)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
aggregate(cc_merge$treatment_group, by=list(cc_merge$year), FUN=length)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
aggregate(cc_merge_covered$treatment_group, by=list(cc_merge_covered$year), FUN=sum)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_merge_covered$did <- cc_merge_covered$treatment_group*cc_merge_covered$treat_year
cc_lm1<-lm(data=cc_merge_covered, 1000*cc_expo_ew~did+factor(year)+factor(ISIN))
cc_lm2<-lm(data=cc_merge_covered, 1000*cc_risk_ew~did+factor(year)+factor(ISIN))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_merge_alt<-filter(cc_merge, is.na(cc_merge$treatment_group))
cc_merge_alt$treatment_group<- FALSE
cc_merge_alt<-rbind(cc_merge_alt, filter(cc_merge, cc_merge$treatment_group))
cc_merge_alt$did <- cc_merge_alt$treatment_group*cc_merge_alt$treat_year
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
aggregate(!cc_merge_alt$treatment_group, by=list(cc_merge_alt$year), FUN=sum)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_lm3<-lm(data=cc_merge_alt, 1000*cc_expo_ew~did+factor(year)+factor(ISIN))
cc_lm4<-lm(data=cc_merge_alt, 1000*cc_risk_ew~did+factor(year)+factor(ISIN))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_merge_copy<-cc_merge
cc_merge_copy[is.na(cc_merge_copy$treatment_group),]$treatment_group<-FALSE

cc_merge_copy$did <- cc_merge_copy$treatment_group*cc_merge_copy$treat_year
cc_lm5<-lm(data=cc_merge_copy, 1000*cc_expo_ew~did+factor(year)+factor(ISIN))
cc_lm6<-lm(data=cc_merge_copy, 1000*cc_risk_ew~did+factor(year)+factor(ISIN))

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(cc_lm5, cc_lm6, omit = c('ISIN',"year"), add.lines=list(c('Firm and Year Fixed effects', 'Yes','Yes')))
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(cc_lm1, cc_lm2,cc_lm3, cc_lm4, omit = c('ISIN',"year"), add.lines=list(c('Firm and Year Fixed effects', 'Yes','Yes','Yes','Yes')))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
temp2<-filter(cc_merge_covered, !treat_year)
temp3<-filter(cc_merge_alt, !treat_year)
temp4<-filter(cc_full, !treat_year)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
condpara6<-lm(1000*cc_risk_ew~treatment_group*factor(year)+factor(ISIN), data=temp2)
condpara7<-lm(1000*cc_risk_ew~treatment_group*factor(year)+factor(ISIN), data=temp3)
condpara8<-lm(1000*cc_risk_ew~treatment_group*factor(year)+factor(ISIN), data=temp4)
stargazer(condpara6, condpara7,condpara8, omit = c('ISIN'), add.lines=list(c('Fixed effects', 'Yes','Yes','Yes'), c("Control Group", "Always Covered", "Never Covered","Both Groups")))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
library('scales')
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
trucost_gind<-read.csv("trucost_gind.csv")
trucost_gind<-subset(trucost_gind, select = c("tic", "gind"))
trucost_gind<-trucost_gind[!duplicated(trucost_gind$tic),]
trucost_gind<-rename(trucost_gind, "ticker" = "tic")
merged_sus_trucost_ind<-merge(merged_sus_trucost, trucost_gind, by = "ticker",all.X = TRUE)
merged_sus_trucost_ind
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
trucost_by_ind_count<-aggregate(merged_sus_trucost_ind$ticker, 
                                by=list(merged_sus_trucost_ind$GICS), FUN=length)
colnames(trucost_by_ind_count)<-c("GICS Industry", "Total Firm-Year Count")
trucost_by_ind_count$`Total Percentage` <- percent(trucost_by_ind_count$`Total Firm-Year Count`/
  sum(trucost_by_ind_count$`Total Firm-Year Count`),0.01)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
temp<-merged_sus_trucost_ind[merged_sus_trucost_ind$treatment_group,]
temp_tab<-aggregate(temp$ticker, by=list(temp$GICS), FUN=length)
colnames(temp_tab)<-c("GICS Industry", "Treatment Firm-Year Count")
temp_tab$`Treated Percentage` <-percent(temp_tab$`Treatment Firm-Year Count`/
  sum(temp_tab$`Treatment Firm-Year Count`),0.01)
trucost_by_ind_count<-merge(trucost_by_ind_count, temp_tab, by = "GICS Industry")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
temp<-merged_sus_trucost_ind[is.na(merged_sus_trucost_ind$treatment_group),]
temp_tab<-aggregate(temp$ticker, by=list(temp$GICS), FUN=length)
colnames(temp_tab)<-c("GICS Industry", "Never Covered Firm-Year Count")
temp_tab$`Never Percentage` <- percent(temp_tab$`Never Covered Firm-Year Count`/
  sum(temp_tab$`Never Covered Firm-Year Count`),0.01)
trucost_by_ind_count<-merge(trucost_by_ind_count, temp_tab, by = "GICS Industry")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
temp<-merged_sus_trucost_ind[!merged_sus_trucost_ind$treatment_group,]
temp_tab<-aggregate(temp$ticker, by=list(temp$GICS), FUN=length)
colnames(temp_tab)<-c("GICS Industry", "Always Covered Firm-Year Count")
temp_tab$`Always Percentage` <- percent(temp_tab$`Always Covered Firm-Year Count`/
  sum(temp_tab$`Always Covered Firm-Year Count`),0.01)
trucost_by_ind_count<-merge(trucost_by_ind_count, temp_tab, by = "GICS Industry")
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
library(xtable)
xtable(trucost_by_ind_count)
```



```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_by_ind_count<-aggregate(cc_merge$ISIN, 
                                by=list(cc_merge$gind), FUN=length)
colnames(cc_by_ind_count)<-c("GICS Industry", "Total Firm-Year Count")
cc_by_ind_count$`Total Percentage` <- percent(cc_by_ind_count$`Total Firm-Year Count`/
  sum(cc_by_ind_count$`Total Firm-Year Count`),0.01)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
temp1<-cc_merge_ind[!is.na(cc_merge$treatment_group),]
temp<-temp1[temp1$treatment_group,]
temp_tab<-aggregate(temp$ISIN, by=list(temp$gind), FUN=length)
colnames(temp_tab)<-c("GICS Industry", "Treatment Firm-Year Count")
temp_tab$`Treated Percentage` <-percent(temp_tab$`Treatment Firm-Year Count`/
  sum(temp_tab$`Treatment Firm-Year Count`),0.01)
cc_by_ind_count<-merge(cc_by_ind_count, temp_tab, by = "GICS Industry")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
temp<-cc_merge_ind[is.na(cc_merge$treatment_group),]
temp_tab<-aggregate(temp$ISIN, by=list(temp$gind), FUN=length)
colnames(temp_tab)<-c("GICS Industry", "Never Covered Firm-Year Count")
temp_tab$`Never Percentage` <- percent(temp_tab$`Never Covered Firm-Year Count`/
  sum(temp_tab$`Never Covered Firm-Year Count`),0.01)
cc_by_ind_count<-merge(cc_by_ind_count, temp_tab, by = "GICS Industry")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
temp<-temp1[!temp1$treatment_group,]
temp_tab<-aggregate(temp$ISIN, by=list(temp$gind), FUN=length)
colnames(temp_tab)<-c("GICS Industry", "Always Covered Firm-Year Count")
temp_tab$`Always Percentage` <- percent(temp_tab$`Always Covered Firm-Year Count`/
  sum(temp_tab$`Always Covered Firm-Year Count`),0.01)
cc_by_ind_count<-merge(cc_by_ind_count, temp_tab, by = "GICS Industry")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
xtable(cc_by_ind_count)
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
is_estimate<-c("Estimated data",
               "Estimate used instead of disclosure - data does not cover global operations")
sum_tab_cols<-subset(merged_sus_trucost,select=c("GHG_Scope1","GHG_Scope2",
                                                 "Absolute_Direct_Indirect",
                                                 "GHG_Scope1_Disclosure", 
                                                 "GHG_Scope2_Disclosure",
                                                 "treatment_group", "Market.Cap"))
sum_tab_cols$log_GHG_Scope1<-log(sum_tab_cols$GHG_Scope1+1)
sum_tab_cols$log_GHG_Scope2<-log(sum_tab_cols$GHG_Scope2+1)
sum_tab_cols$log_Absolute_Direct_Indirect<-log(sum_tab_cols$Absolute_Direct_Indirect+0.001)
sum_tab_cols$Market.Cap<-log(sum_tab_cols$Market.Cap)
sum_tab_cols$GHG_Scope1_Disclosure<-as.integer(!sum_tab_cols$GHG_Scope1_Disclosure %in% is_estimate)
sum_tab_cols$GHG_Scope2_Disclosure<-as.integer(!sum_tab_cols$GHG_Scope2_Disclosure %in% is_estimate)
summary(sum_tab_cols[!is.na(sum_tab_cols$treatment_group),])
summary(sum_tab_cols)
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
sum_tab_cols_nona<-sum_tab_cols[!is.na(sum_tab_cols$treatment_group),]
summary(sum_tab_cols_nona[sum_tab_cols_nona$treatment_group,])
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
sum_tab_cc_cols<-subset(cc_merge,select=c("cc_expo_ew","cc_risk_ew","Market.Cap","treatment_group"))
sum_tab_cc_cols$cc_expo_ew<-sum_tab_cc_cols$cc_expo_ew*1000
sum_tab_cc_cols$cc_risk_ew<-sum_tab_cc_cols$cc_risk_ew*1000
sum_tab_cc_cols$Market.Cap<-log(sum_tab_cc_cols$Market.Cap)
summary(sum_tab_cc_cols[is.na(sum_tab_cc_cols$treatment_group),])
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
sum_tab_cc_cols_nona<-sum_tab_cc_cols[!is.na(sum_tab_cc_cols$treatment_group),]
summary(sum_tab_cc_cols_nona[!sum_tab_cc_cols_nona$treatment_group,])
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
trucost_sus_always_covered$high_esg <- trucost_sus_always_covered$`16f`>49
trucost_sus_always_covered$low_esg <- trucost_sus_always_covered$`16f`<=49
trucost_sus_always_covered$high_esg_did<-trucost_sus_always_covered$high_esg*
  trucost_sus_always_covered$did
trucost_sus_always_covered$low_esg_did <- trucost_sus_always_covered$low_esg*
  trucost_sus_always_covered$did
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
trucost_sus_always_covered$size<-gsub( " .*$", "", trucost_sus_always_covered$Equity..Style.Box..Long. )

trucost_sus_always_covered$is_large<-(trucost_sus_always_covered$size == "Large")
trucost_sus_always_covered$large_did <- 
  (trucost_sus_always_covered$size == "Large")*trucost_sus_always_covered$did

trucost_sus_always_covered$small_did <- 
  (trucost_sus_always_covered$size != "Large")*trucost_sus_always_covered$did
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_size_scope1<-lm(formula =log(GHG_Scope1+1)~did*is_large+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_size_scope2<-lm(formula =log(GHG_Scope2+1)~did*is_large+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_size_total<-lm(formula =log(Absolute_Direct_Indirect+0.001)~did*is_large+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(always_cov_firm_ff_size_scope1, 
          always_cov_firm_ff_size_scope2, 
          always_cov_firm_ff_size_total, omit = c('year','Company.Name'), 
          add.lines=list(c('Year and Firm Fixed Effects', 'Yes','Yes','Yes'), 
                         c("Control Group", "Always Covered", "Always Covered", "Always Covered")))
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_esg_scope1<-lm(formula =log(GHG_Scope1+1)~high_esg_did+low_esg_did+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_esg_scope2<-lm(formula =log(GHG_Scope2+1)~high_esg_did+low_esg_did+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
always_cov_firm_ff_esg_total<-lm(formula=log(Absolute_Direct_Indirect+0.001)~
                                   high_esg_did+low_esg_did+factor(year)
                      +factor(Company.Name), data = trucost_sus_always_covered)

```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(always_cov_firm_ff_esg_total,
          always_cov_firm_ff_esg_scope1,
          always_cov_firm_ff_esg_scope2, 
          omit = c('year','Company.Name'), 
          add.lines=list(c('Year and Firm Fixed Effects', 'Yes','Yes','Yes'), 
                         c("Control Group", "Always Covered", "Always Covered", "Always Covered")))
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_merge_covered$high_esg <- cc_merge_covered$`16f`>49
cc_merge_covered$low_esg <- cc_merge_covered$`16f`<=49
cc_merge_covered$high_esg_did<-cc_merge_covered$high_esg*
  cc_merge_covered$did
cc_merge_covered$low_esg_did <- cc_merge_covered$low_esg*
  cc_merge_covered$did

cc_merge_covered$high_esg_treatment<-cc_merge_covered$high_esg*
  cc_merge_covered$treatment_group
cc_merge_covered$low_esg_treatment <- cc_merge_covered$low_esg*
cc_merge_covered$treatment_group
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_merge_covered$size<-gsub( " .*$", "", cc_merge_covered$Equity..Style.Box..Long. )

cc_merge_covered$is_large<-(cc_merge_covered$size == "Large")
cc_merge_covered$large_did <- 
  (cc_merge_covered$size == "Large")*cc_merge_covered$did

cc_merge_covered$small_did <- 
  (cc_merge_covered$size != "Large")*cc_merge_covered$did
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_size_expo<-lm(formula =1000*cc_expo_ew~did*is_large+factor(year)
                      +factor(ISIN), data = cc_merge_covered)

cc_size_risk<-lm(formula =1000*cc_risk_ew~did*is_large+factor(year)
                      +factor(ISIN), data = cc_merge_covered)

```



```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(cc_size_expo,
         cc_size_risk, omit = c('year','ISIN'), 
          add.lines=list(c('Year and Firm Fixed Effects', 'Yes','Yes'), 
                         c("Control Group","Always Covered", "Always Covered")))
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_esg_lm1<-lm(data=cc_merge_covered, 1000*cc_expo_ew~high_esg_did+low_esg_did
               +factor(year)+factor(ISIN))
cc_esg_lm2<-lm(data=cc_merge_covered, 1000*cc_risk_ew~high_esg_did+low_esg_did
               +factor(year)+factor(ISIN))
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
stargazer(cc_esg_lm1,
          cc_esg_lm2, 
          omit = c('year','ISIN'), 
          add.lines=list(c('Year and Firm Fixed Effects','Yes','Yes'), 
                         c("Control Group", "Always Covered", "Always Covered")))
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
trucost_sus_always_covered$high_esg_treatment<-trucost_sus_always_covered$high_esg*
  trucost_sus_always_covered$treatment_group
trucost_sus_always_covered$low_esg_treatment <- trucost_sus_always_covered$low_esg*
  trucost_sus_always_covered$treatment_group
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
both_firm_ff_year_scope1<-lm(formula =log(GHG_Scope1+1)~factor(year)*high_esg_treatment+factor(year)*low_esg_treatment
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
both_firm_ff_year_scope2<-lm(formula =log(GHG_Scope2+1)~factor(year)*high_esg_treatment+factor(year)*low_esg_treatment
                      +factor(Company.Name), data = trucost_sus_always_covered)

```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
scope1_ci_results<-data.frame(tail(summary(both_firm_ff_year_scope1)$coefficients,n=12)[,1:2])
scope2_ci_results<-data.frame(tail(summary(both_firm_ff_year_scope2)$coefficients,n=12)[,1:2])

scope1_ci_results$upper<-scope1_ci_results$Estimate+3*scope1_ci_results$Std..Error
scope1_ci_results$lower<-scope1_ci_results$Estimate-3*scope1_ci_results$Std..Error
scope1_ci_results$group<-NA
scope1_ci_results[1:6,]$group<-"High ESG"
scope1_ci_results[7:12,]$group<-"Low ESG"
scope1_ci_results$year<-1:12
scope1_ci_results$year<-2014+(scope1_ci_results$year-1)%%6

scope2_ci_results$upper<-scope2_ci_results$Estimate+3*scope2_ci_results$Std..Error
scope2_ci_results$lower<-scope2_ci_results$Estimate-3*scope2_ci_results$Std..Error
scope2_ci_results$group<-NA
scope2_ci_results[1:6,]$group<-"High ESG"
scope2_ci_results[7:12,]$group<-"Low ESG"
scope2_ci_results$year<-1:12
scope2_ci_results$year<-2014+(scope2_ci_results$year-1)%%6
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
ggplot(scope1_ci_results,aes(x = year, y = Estimate, group = group, color = group))+
  geom_point(position = position_dodge(width = .4))+
  geom_errorbar(aes(ymin = lower, ymax = upper),position = position_dodge(width = .4))+
  geom_hline(yintercept = 0)+
  scale_color_manual(values=c("#3377FF", "#FA1F15"))+ylim(-0.8, 1)+
  theme_minimal()+ggtitle("Estimated Treatment Effect with 99% CI, log Scope1")
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
ggplot(scope2_ci_results,aes(x = year, y = Estimate, group = group, color = group))+
  geom_point(position = position_dodge(width = .4))+
  geom_errorbar(aes(ymin = lower, ymax = upper),position = position_dodge(width = .4))+
  geom_hline(yintercept = 0)+
  scale_color_manual(values=c("#3377FF", "#FA1F15"))+ylim(-0.8, 1)+
  theme_minimal()+ggtitle("Estimated Treatment Effect with 99% CI, log Scope2")
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
cc_esg_lm1_year<-lm(data=cc_merge_covered, 1000*cc_expo_ew~high_esg_treatment*factor(year)+
               low_esg_treatment*factor(year)+factor(ISIN))
cc_esg_lm2_year<-lm(data=cc_merge_covered, 1000*cc_risk_ew~high_esg_treatment*factor(year)+
               low_esg_treatment*factor(year)+factor(ISIN))
```


```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
expo_ci_results<-data.frame(tail(summary(cc_esg_lm1_year)$coefficients,n=12)[,1:2])
risk_ci_results<-data.frame(tail(summary(cc_esg_lm2_year)$coefficients,n=12)[,1:2])

expo_ci_results$upper<-expo_ci_results$Estimate+3*expo_ci_results$Std..Error
expo_ci_results$lower<-expo_ci_results$Estimate-3*expo_ci_results$Std..Error
expo_ci_results$group<-NA
expo_ci_results[1:6,]$group<-"High ESG"
expo_ci_results[7:12,]$group<-"Low ESG"
expo_ci_results$year<-1:12
expo_ci_results$year<-2014+(expo_ci_results$year-1)%%6

risk_ci_results$upper<-risk_ci_results$Estimate+3*risk_ci_results$Std..Error
risk_ci_results$lower<-risk_ci_results$Estimate-3*risk_ci_results$Std..Error
risk_ci_results$group<-NA
risk_ci_results[1:6,]$group<-"High ESG"
risk_ci_results[7:12,]$group<-"Low ESG"
risk_ci_results$year<-1:12
risk_ci_results$year<-2014+(risk_ci_results$year-1)%%6
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
ggplot(expo_ci_results,aes(x = year, y = Estimate, group = group, color = group))+
  geom_point(position = position_dodge(width = .4))+
  geom_errorbar(aes(ymin = lower, ymax = upper),position = position_dodge(width = .4))+
  geom_hline(yintercept = 0)+
  scale_color_manual(values=c("#3377FF", "#FA1F15"))+ylim(-0.8, 1)+
  theme_minimal()+ggtitle("Estimated Treatment Effect with 99% CI, Exposure")
```

```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
ggplot(risk_ci_results,aes(x = year, y = Estimate, group = group, color = group))+
  geom_point(position = position_dodge(width = .4))+
  geom_errorbar(aes(ymin = lower, ymax = upper),position = position_dodge(width = .4))+
  geom_hline(yintercept = 0)+
  scale_color_manual(values=c("#3377FF", "#FA1F15"))+ylim(-0.2, 0.2)+
  theme_minimal()+ggtitle("Estimated Treatment Effect with 99% CI, Risk")
```
